export const BLOCKED_DOMAINS = new Set([
  "example.com",
  "example.net",
  "example.org",
  "test.com",
  "email.com",
  "domain.com",
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "sharklasers.com",
  "grr.la",
  "10minutemail.com",
  "10minutemail.net",
  "tempmail.com",
  "temp-mail.org",
  "tempmailo.com",
  "tempr.email",
  "throwawaymail.com",
  "yopmail.com",
  "yopmail.net",
  "getnada.com",
  "nada.email",
  "dispostable.com",
  "fakeinbox.com",
  "trashmail.com",
  "trashmail.de",
  "mailnesia.com",
  "maildrop.cc",
  "mailcatch.com",
  "moakt.com",
  "mohmal.com",
  "spamgourmet.com",
  "mytemp.email",
  "emailondeck.com",
  "burnermail.io",
  "inboxkitten.com",
  "harakirimail.com",
  "1secmail.com",
  "1secmail.net",
  "1secmail.org",
  "linshiyouxiang.net",
  "discard.email",
  "mailde.de",
  "spam4.me",
  "byom.de",
]);

export const BLOCKED_TLDS = new Set([
  "invalid",
  "local",
  "localhost",
  "test",
  "example",
]);

const TYPO_DOMAINS: Record<string, string> = {
  "gmial.com": "gmail.com",
  "gmai.com": "gmail.com",
  "gmail.co": "gmail.com",
  "gmail.con": "gmail.com",
  "gmail.cm": "gmail.com",
  "gnail.com": "gmail.com",
  "gmaill.com": "gmail.com",
  "hotmial.com": "hotmail.com",
  "hotmai.com": "hotmail.com",
  "hotmail.co": "hotmail.com",
  "hotmail.con": "hotmail.com",
  "outlok.com": "outlook.com",
  "outloo.com": "outlook.com",
  "outlook.co": "outlook.com",
  "yaho.com": "yahoo.com",
  "yahoo.co": "yahoo.com",
  "yahoo.con": "yahoo.com",
  "iclod.com": "icloud.com",
  "icloud.co": "icloud.com",
  "protonmai.com": "protonmail.com",
};

export function suggestDomain(domain: string): string | null {
  if (!Object.hasOwn(TYPO_DOMAINS, domain)) return null;
  const suggestion = TYPO_DOMAINS[domain];
  return typeof suggestion === "string" ? suggestion : null;
}
